[project]
name = "hotspot-api"
version = "0.1.0"
description = "API backend for hotspot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "uvicorn[standard]>=0.35.0",
]
